name: Create Archive
on: [push]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: rm -r .git
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: FumpleResourcePack
        path: .
