name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'fumpleresourcepack.zip'
        exclusions: '*.git*'
    - name: Upload Archive
    - uses: actions/upload-artifact@v2
      with:
        name: ResourcePack
        path: fumpleresourcepack.zip
